"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "mr" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar & Common
    carelink: "carelink",
    doctorPortal: "Doctor Portal",
    patientPortal: "Patient Portal",
    doctorLogin: "Doctor Login",
    patientLogin: "Patient Login",
    logout: "Log Out",
    abhaVerified: "ABHA Verified",
    abhaId: "ABHA ID",
    step1of3: "Step 1 of 3",
    close: "Close",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    edit: "Edit",
    print: "Print",
    status: "Status",
    view: "View",
    open: "Open",
    explore: "Explore",

    // Login Page
    careJourney: "Care Journey",
    healthInOnePlace: "Your health, in one place",
    healthInOnePlaceDesc: "Keep your medical history close, so every care decision can feel a little more personal.",
    welcomeBack: "Welcome back",
    continueCareJourney: "Let's continue your care journey.",
    signInSubtitle: "Sign in to access your medical history and personalized care.",
    loginWithAbha: "Login with ABHA",
    loginWithMobile: "Login with mobile",
    enterAbhaId: "Enter your ABHA ID",
    enterMobileNumber: "Enter your mobile number",
    verifyAndSignIn: "Verify & Sign In",
    newToAbha: "New to ABHA?",
    createAbhaDesc: "Create your Ayushman Bharat Health Account in 2 minutes.",
    createAbha: "Create ABHA",
    doctorOrHospitalStaff: "Doctor or Hospital Staff?",
    accessDoctorWorkstation: "Access the Doctor Workstation and OPD consultation desk.",
    switchToDoctorLogin: "Go to Doctor Portal →",
    switchToPatientLogin: "Go to Patient Portal →",

    // Doctor Login
    doctorPortalTitle: "Clinical care, streamlined",
    doctorPortalDesc: "Access consultation records, write prescriptions, and review patient histories securely.",
    doctorSignInHeading: "Doctor Sign In",
    doctorSignInDesc: "Enter your registered mobile number to access your consultation workstation.",
    registeredMobileNumber: "Registered Mobile Number",
    verifyDoctorLogin: "Verify & Open Workstation",
    areYouPatient: "Are you a patient?",
    patientPortalRedirect: "Sign in with your ABHA ID or mobile number on the Patient Portal.",

    // Profile Card
    confirmProfileDetails: "Confirm your profile details",
    profileReviewDesc: "Review the personal information retrieved from your ABHA record before proceeding.",
    personalDetails: "Personal Details",
    fullName: "Full Name",
    age: "Age",
    gender: "Gender",
    abhaAddress: "ABHA Address",
    confirmAndContinue: "Confirm & Continue",
    notYouSwitch: "Not you? Switch Account",

    // Consent Screen
    step2of3: "Step 2 of 3",
    abdmConsentRequest: "ABDM Consent Request",
    consentRequestSubtitle: "Carelink requests access to your health records for AI-assisted clinical consultation.",
    whatWeCollect: "What we collect",
    whatWeCollectDesc: "Your voice responses, symptoms and uploaded clinical documents.",
    howItIsUsed: "How it is used",
    howItIsUsedDesc: "To prepare your consultation token and clinical summary for the attending doctor.",
    dataProtection: "Data protection",
    dataProtectionDesc: "End-to-end encrypted under ABDM Health Data Management Policy.",
    grantConsent: "Grant Consent & Continue",
    declineConsent: "Decline & Go Back",

    // Patient Dashboard Header
    goodMorning: "Good morning",
    portalSubtitle: "Your active consultation token and digital medical record are up to date.",
    startNewCase: "Start New Case",
    aiIntake: "AI Intake",
    startNewConsultation: "Start New Consultation",

    // Tabs
    overview: "Overview",
    timeline: "Timeline",
    addHistory: "Add History",
    familyTree: "Family Tree",
    settings: "Settings",

    // Quick Action Cards
    doctorScannerTitle: "Doctor Desk Scanner",
    doctorScannerDesc: "Scan room QR badge upon entering OPD",
    healthTimelineTitle: "Health Timeline",
    healthTimelineDesc: "recorded visits & clinical tests",
    addHistoryTitle: "Add Medical History",
    addHistoryDesc: "Upload past reports, OCR & records",
    familyTreeTitle: "Family Tree",
    familyTreeDesc: "linked family health profiles",

    // Active Token Card
    consultationToken: "Consultation Token",
    currentActiveToken: "Current Active Token",
    noActiveConsultation: "No Active Consultation",
    noActiveConsultationDesc: "Start an AI clinical intake or scan any doctor desk QR badge to consult the doctor.",
    readyToStart: "Ready to Start",
    activeConsultation: "Active Consultation",
    checkedInViaQr: "Checked-in via Room QR",
    awaitingQrCheckIn: "Awaiting Room QR Check-in",
    consultationStatus: "Consultation Status",
    attendingOpd: "Attending Doctor / OPD",
    nonePendingQr: "None (Scan Desk QR)",
    viewToken: "View Token",
    scanRoomQr: "Scan Room QR",
    myConsultationCases: "My Consultation Cases",
    makeNewCase: "Make New Case",
    scanDoctorQrToComplete: "Scan Doctor Desk QR code to complete desk check-in.",
    scanAnyDoctorPrompt: "Point camera or scan any OPD doctor desk QR badge.",
    completed: "Completed",
    awaitingRoomQr: "Awaiting Room QR",
    checkedIn: "Checked In",
    physician: "Physician",
    created: "Created",
    scanner: "Scanner",
    ayushHolistic: "AYUSH Holistic",
    generalMedicine: "General Medicine",
    chronologicalRecord: "Chronological Record",
    digitalHealthTimeline: "Digital Health Timeline",
    timelineSubtitle: "Synced through ABDM health records and verified OPD doctor visits.",
    noRecordsFound: "No records found",
    noRecordsDesc: "Complete a consultation or use \"+ Add History\" to attach records.",
    selfReportedRecords: "Self-Reported Health Records",
    addPastMedicalRecord: "Add Past Medical Record & Report",
    addPastMedicalRecordDesc: "Upload lab reports, discharge summaries, or previous prescriptions to sync with ABHA.",
    familyMedicalTree: "Family Medical Tree & Hereditary Profile",

    // Scanner Modal
    scannerTitle: "Doctor Desk QR Scanner",
    scannerSubtitle: "Point camera or test-scan any doctor desk QR badge to check in.",
    verifiedDoctorDesk: "Verified Doctor Desk",
    checkInExistingCase: "Check-In Existing Case",
    startNewCaseForDoctor: "Start New Case for Doctor",
    scanDifferentDoctor: "Scan a different doctor code",
    alignDoctorQr: "Align doctor desk QR inside viewfinder",
    verifyQr: "Verify QR",
    enterRoomCode: "Enter Room Code (e.g. OPD-DEMOCARE-3)",
    quickTestPresets: "Tap 1-click test doctor QR badge:",

    // Family Tree
    familyHealthNetwork: "Family Health Network",
    familyTreeSubtitle: "Track linked family ABHA accounts to identify hereditary health patterns and coordinate care.",
    addFamilyMember: "Add Family Member",
    consentLinkedAbdm: "Consent Linked (ABDM)",
    hereditaryInsight: "Family Hereditary Health Insight",
    hereditaryDesc: "Hypertension and Type 2 Diabetes recorded in direct lineage. Regular screening recommended for Shriram.",
    selfPatient: "Self (Patient)",
    sendConsentRequest: "Send Link Request via ABDM",
    simulateAccept: "Simulate Member Acceptance",
    requestSent: "Consent request sent to relative's ABHA ID. Awaiting acceptance...",
    memberLinkedSuccess: "Family member linked successfully to your health tree!",

    // Summary Token
    medicalHistoryReady: "Your medical history is ready",
    medicalHistoryReadyDesc: "Your doctor can now review your health history and symptoms before calling you into the consultation.",
    tokenNumberLabel: "Your Token Number",
    assignedOpdLabel: "Assigned OPD Desk",
    tokenActiveNote: "Your consultation token is active. Proceed to OPD Room when called.",
    caseForwardedNote: "Consultation Ready · Case details forwarded to Doctor Workstation",
    backToDashboard: "Back to Dashboard",
    synchronizedWithAbdm: "Synchronized with ABDM",

    // Doctor Dashboard & Workstation
    doctorWorkstation: "Doctor Workstation",
    todaysConsultations: "Today's Active Consultations",
    todayAppointments: "Today's Appointments",
    viewAllPatients: "View all patients →",
    patientDirectory: "Patient Directory",
    patientsAndRecords: "Patients & Clinical Records",
    patientsDirectoryDesc: "Review registered patient files, ongoing cases, and ABDM linked health histories.",
    deskQrPlacard: "Desk QR Placard",
    pendingReviews: "Cases Awaiting Review",
    completedVisits: "Completed Visits",
    activeDoctorCode: "Active Doctor Desk Code",
    showDeskQr: "Show Desk QR",
    copyDeskCode: "Copy Desk Code",
    openCase: "Open Case",
    openFile: "Open File",
    review: "Review",
    filterAll: "All Patients",
    filterActive: "Active",
    filterRecent: "Recent",
    backToDirectory: "Back to patient directory",
    caseDetails: "Case Details",
    healthTimelineTab: "Health Timeline",
    familyTreeTab: "Family Tree",
    aiIntakeSummary: "AI Case Intake Summary",
    verifiedViaIntake: "Verified via AI Clinical Intake Dialogue",
    patientChiefComplaint: "Patient Chief Complaint",
    durationAndSeverity: "Duration & Severity",
    reportedSymptoms: "Reported Symptoms & Notes",
    clinicalVitals: "Clinical Vitals",
    ocrDocumentsAttached: "Attached OCR Clinical Documents",
    clinicalDiagnosis: "Clinical Diagnosis",
    diagnosisPlaceholder: "Enter primary clinical diagnosis (e.g. Acute Bronchitis)...",
    doctorNotes: "Doctor Clinical Notes & Advice",
    notesPlaceholder: "Enter clinical observation, lifestyle advice, follow-up recommendations...",
    prescribedMedications: "Prescribed Medications",
    addMedication: "Add Medicine",
    medicineName: "Medicine Name",
    dosage: "Dosage",
    frequency: "Frequency",
    duration: "Duration",
    instructions: "Instructions",
    editIntakeData: "Edit / Correct Intake Data",
    printCaseSummary: "Print Case Summary & Rx",
    confirmAndComplete: "Confirm & Complete Consultation",
    consultationCompletedMsg: "Consultation marked completed and record synchronized.",
  },

  mr: {
    // Navbar & Common
    carelink: "केअरलिंक",
    doctorPortal: "डॉक्टर पोर्टल",
    patientPortal: "रुग्ण पोर्टल",
    doctorLogin: "डॉक्टर लॉगिन",
    patientLogin: "रुग्ण लॉगिन",
    logout: "बाहेर पडा (Logout)",
    abhaVerified: "आभा सत्यापित",
    abhaId: "आभा आयडी",
    step1of3: "टप्पा १ पैकी ३",
    close: "बंद करा",
    cancel: "रद्द करा",
    confirm: "पुष्टी करा",
    save: "जतन करा",
    edit: "संपादित करा",
    print: "प्रिंट करा",
    status: "स्थिती",
    view: "पहा",
    open: "उघडा",
    explore: "तपासा",

    // Login Page
    careJourney: "आरोग्य प्रवास",
    healthInOnePlace: "तुमचे आरोग्य, एकाच ठिकाणी",
    healthInOnePlaceDesc: "तुमचा वैद्यकीय इतिहास जवळ ठेवा, जेणेकरून उपचाराचा प्रत्येक निर्णय अधिक योग्य होईल.",
    welcomeBack: "पुन्हा स्वागत आहे",
    continueCareJourney: "तुमचा आरोग्य प्रवास सुरू ठेवूया.",
    signInSubtitle: "वैद्यकीय इतिहास आणि वैयक्तिक उपचारांसाठी लॉगिन करा.",
    loginWithAbha: "आभा (ABHA) द्वारे लॉगिन",
    loginWithMobile: "मोबाईल क्रमांकाने लॉगिन",
    enterAbhaId: "तुमचा आभा (ABHA) आयडी टाका",
    enterMobileNumber: "तुमचा मोबाईल नंबर प्रविष्ट करा",
    verifyAndSignIn: "सत्यापित करा व पुढे जा",
    newToAbha: "आभा खाते नवीन आहे का?",
    createAbhaDesc: "२ मिनिटांत तुमचे आयुष्मान भारत आरोग्य खाते (ABHA) तयार करा.",
    createAbha: "नवीन आभा तयार करा",
    doctorOrHospitalStaff: "डॉक्टर किंवा रुग्णालय कर्मचारी आहात का?",
    accessDoctorWorkstation: "डॉक्टर वर्कस्टेशन आणि ओपीडी कन्सल्टेशन डेस्क उघडा.",
    switchToDoctorLogin: "डॉक्टर पोर्टलवर जा →",
    switchToPatientLogin: "रुग्ण पोर्टलवर जा →",

    // Doctor Login
    doctorPortalTitle: "क्लिनिकल काळजी, सुलभ आणि जलद",
    doctorPortalDesc: "सल्लामसलत रेकॉर्ड पहा, प्रिस्क्रिप्शन लिहा आणि रुग्णांचा इतिहास सुरक्षितपणे तपासा.",
    doctorSignInHeading: "डॉक्टर लॉगिन",
    doctorSignInDesc: "तुमच्या कन्सल्टेशन वर्कस्टेशनमध्ये प्रवेश करण्यासाठी नोंदणीकृत मोबाईल नंबर टाका.",
    registeredMobileNumber: "नोंदणीकृत मोबाईल नंबर",
    verifyDoctorLogin: "सत्यापित करा व वर्कस्टेशन उघडा",
    areYouPatient: "तुम्ही रुग्ण आहात का?",
    patientPortalRedirect: "रुग्ण पोर्टलवर आभा आयडी किंवा मोबाईल नंबरने लॉगिन करा.",

    // Profile Card
    confirmProfileDetails: "तुमच्या प्रोफाईल तपशीलांची पुष्टी करा",
    profileReviewDesc: "पुढे जाण्यापूर्वी तुमच्या आभा रेकॉर्डमधून मिळवलेली माहिती तपासा.",
    personalDetails: "वैयक्तिक तपशील",
    fullName: "पूर्ण नाव",
    age: "वय",
    gender: "लिंग",
    abhaAddress: "आभा पत्ता (ABHA Address)",
    confirmAndContinue: "पुष्टी करा आणि पुढे जा",
    notYouSwitch: "तुम्ही नाही आहात? खाते बदला",

    // Consent Screen
    step2of3: "टप्पा २ पैकी ३",
    abdmConsentRequest: "ABDM संमती विनंती",
    consentRequestSubtitle: "AI-आधारित सल्लामसलतीसाठी केअरलिंक तुमच्या आरोग्य नोंदींची संमती मागते.",
    whatWeCollect: "आम्ही काय गोळा करतो",
    whatWeCollectDesc: "तुमचे आवाज प्रतिसाद, लक्षणे आणि अपलोड केलेले वैद्यकीय अहवाल.",
    howItIsUsed: "याचा वापर कसा केला जातो",
    howItIsUsedDesc: "तपासणी टोकन आणि डॉक्टरांसाठी क्लिनिकल सारांश तयार करण्यासाठी.",
    dataProtection: "डेटा सुरक्षा आणि गोपनीयता",
    dataProtectionDesc: "ABDM आरोग्य डेटा व्यवस्थापन धोरणांतर्गत पूर्णपणे कूटबद्ध (Encrypted).",
    grantConsent: "संमती द्या आणि पुढे जा",
    declineConsent: "नकार द्या आणि मागे जा",

    // Patient Dashboard Header
    goodMorning: "शुभ सकाळ",
    portalSubtitle: "तुमचे सक्रिय सल्लामसलत टोकन आणि डिजिटल वैद्यकीय रेकॉर्ड अद्ययावत आहेत.",
    startNewCase: "+ नवीन केस तयार करा",
    aiIntake: "AI तपासणी",
    startNewConsultation: "नवीन सल्लामसलत सुरू करा",

    // Tabs
    overview: "विहंगावलोकन",
    timeline: "टाईमलाईन",
    addHistory: "इतिहास जोडा",
    familyTree: "कुटुंब वृक्ष (Family Tree)",
    settings: "सेटिंग्ज",

    // Quick Action Cards
    doctorScannerTitle: "डॉक्टर QR स्कॅनर",
    doctorScannerDesc: "ओपीडी खोलीत प्रवेश करताना QR स्कॅन करा",
    healthTimelineTitle: "आरोग्य टाईमलाईन",
    healthTimelineDesc: "नोंदणीकृत भेटी आणि चाचण्या",
    addHistoryTitle: "वैद्यकीय इतिहास जोडा",
    addHistoryDesc: "मागील रिपोर्ट्स व OCR अपलोड करा",
    familyTreeTitle: "कुटुंब वृक्ष",
    familyTreeDesc: "जोडलेली कौटुंबिक आरोग्य खाती",

    // Active Token Card
    consultationToken: "सल्लामसलत टोकन",
    currentActiveToken: "सक्रिय तपासणी टोकन",
    noActiveConsultation: "सध्या कोणतीही सक्रिय केस नाही",
    noActiveConsultationDesc: "डॉक्टरांशी सल्लामसलत करण्यासाठी AI तपासणी सुरू करा किंवा डॉक्टरांचा QR कोड स्कॅन करा.",
    readyToStart: "सुरू करण्यास सज्ज",
    activeConsultation: "सक्रिय सल्लामसलत",
    checkedInViaQr: "खोली QR द्वारे चेक-इन झाले",
    awaitingQrCheckIn: "खोली QR स्कॅन प्रलंबित",
    consultationStatus: "सल्लामसलत स्थिती",
    attendingOpd: "तपासणारे डॉक्टर / ओपीडी",
    nonePendingQr: "कोणी नाही (QR स्कॅन करा)",
    viewToken: "टोकन पहा",
    scanRoomQr: "खोली QR स्कॅन करा",
    myConsultationCases: "माझ्या वैद्यकीय केसेस",
    makeNewCase: "+ नवीन केस नोंदवा",
    scanDoctorQrToComplete: "डेस्क चेक-इन पूर्ण करण्यासाठी डॉक्टरांचा QR कोड स्कॅन करा.",
    scanAnyDoctorPrompt: "कॅमेरा समोर धरा किंवा कोणत्याही ओपीडी डॉक्टर डेस्कचा QR स्कॅन करा.",
    completed: "पूर्ण झाले",
    awaitingRoomQr: "खोली QR ची प्रतीक्षा",
    checkedIn: "तपासणीसाठी हजर",
    physician: "डॉक्टर",
    created: "नोंदणी",
    scanner: "स्कॅनर",
    ayushHolistic: "आयुष समग्र",
    generalMedicine: "सामान्य औषधोपचार",
    chronologicalRecord: "कालक्रमानुसार नोंद",
    digitalHealthTimeline: "डिजिटल आरोग्य टाइमलाइन",
    timelineSubtitle: "ABDM आरोग्य नोंदी आणि तपासलेल्या OPD भेटींसह समक्रमित.",
    noRecordsFound: "कोणतीही नोंद आढळली नाही",
    noRecordsDesc: "सल्ला पूर्ण करा किंवा नोंदी जोडण्यासाठी \"+ इतिहास जोडा\" वापरा.",
    selfReportedRecords: "स्वयं-नोंदवलेले आरोग्य रेकॉर्ड",
    addPastMedicalRecord: "मागील वैद्यकीय नोंद आणि अहवाल जोडा",
    addPastMedicalRecordDesc: "ABHA सह समक्रमित करण्यासाठी लॅब अहवाल किंवा मागील प्रिस्क्रिप्शन अपलोड करा.",
    familyMedicalTree: "कौटुंबिक वैद्यकीय वृक्ष आणि आनुवंशिक प्रोफाइल",

    // Scanner Modal
    scannerTitle: "डॉक्टर डेस्क QR स्कॅनर",
    scannerSubtitle: "कॅमेरा समोर धरा किंवा कोणत्याही डॉक्टर डेस्कचा QR कोड स्कॅन करा.",
    verifiedDoctorDesk: "सत्यापित डॉक्टर डेस्क",
    checkInExistingCase: "विद्यमान केस चेक-इन करा",
    startNewCaseForDoctor: "या डॉक्टरांसाठी नवीन केस सुरू करा",
    scanDifferentDoctor: "दुसरा डॉक्टर कोड स्कॅन करा",
    alignDoctorQr: "डॉक्टरांचा QR कोड बॉक्समध्ये संरेखित करा",
    verifyQr: "QR सत्यापित करा",
    enterRoomCode: "खोली कोड प्रविष्ट करा (उदा. OPD-DEMOCARE-3)",
    quickTestPresets: "१-क्लिक चाचणी डॉक्टर QR बॅज:",

    // Family Tree
    familyHealthNetwork: "कौटुंबिक आरोग्य नेटवर्क",
    familyTreeSubtitle: "वारसदार आजार ओळखण्यासाठी आणि काळजी घेण्यासाठी कुटुंबाची आभा खाती जोडा.",
    addFamilyMember: "+ कुटुंब सदस्य जोडा",
    consentLinkedAbdm: "संमती जोडली (ABDM)",
    hereditaryInsight: "कौटुंबिक आनुवंशिक आरोग्य विश्लेषण",
    hereditaryDesc: "कुटुंबात उच्च रक्तदाब व मधुमेहाचा इतिहास आहे. श्रीराम यांच्यासाठी नियमित तपासणीची शिफारस केली जाते.",
    selfPatient: "स्वतः (रुग्ण)",
    sendConsentRequest: "ABDM द्वारे संमती विनंती पाठवा",
    simulateAccept: "सदस्याची संमती स्वीकृती सिम्युलेट करा",
    requestSent: "नातेवाईकांच्या आभा आयडीवर संमती विनंती पाठवली आहे. मंजुरीची प्रतीक्षा...",
    memberLinkedSuccess: "कुटुंब सदस्य यशस्वीरित्या कुटुंब वृक्षात जोडला गेला!",

    // Summary Token
    medicalHistoryReady: "तुमचा वैद्यकीय इतिहास तयार आहे",
    medicalHistoryReadyDesc: "तुम्हाला आत बोलावण्यापूर्वी डॉक्टर तुमचा आरोग्य इतिहास आणि लक्षणे तपासू शकतात.",
    tokenNumberLabel: "तुमचा टोकन क्रमांक",
    assignedOpdLabel: "नियुक्त ओपीडी डेस्क",
    tokenActiveNote: "तुमचे टोकन सक्रिय आहे. बोलावल्यावर ओपीडी खोलीत जा.",
    caseForwardedNote: "तपासणी सज्ज · केस तपशील डॉक्टरांच्या वर्कस्टेशनवर पाठवले आहेत",
    backToDashboard: "डॅशबोर्डवर परत जा",
    synchronizedWithAbdm: "ABDM सह समक्रमित",

    // Doctor Dashboard & Workstation
    doctorWorkstation: "डॉक्टर वर्कस्टेशन",
    todaysConsultations: "आजच्या सक्रिय सल्लामसलती",
    todayAppointments: "आजच्या भेटी",
    viewAllPatients: "सर्व रुग्ण पहा →",
    patientDirectory: "रुग्ण निर्देशिका",
    patientsAndRecords: "रुग्ण आणि क्लिनिकल रेकॉर्ड",
    patientsDirectoryDesc: "नोंदणीकृत रुग्ण फाईल्स, चालू केसेस आणि आभा संलग्न इतिहास तपासा.",
    deskQrPlacard: "डेस्क QR फलक",
    pendingReviews: "पुनरावलोकनासाठी प्रलंबित",
    completedVisits: "पूर्ण झालेल्या भेटी",
    activeDoctorCode: "सक्रिय डॉक्टर डेस्क कोड",
    showDeskQr: "डेस्क QR दाखवा",
    copyDeskCode: "डेस्क कोड कॉपी करा",
    openCase: "केस उघडा",
    openFile: "फाईल उघडा",
    review: "तपासा",
    filterAll: "सर्व रुग्ण",
    filterActive: "सक्रिय",
    filterRecent: "नुकतेच",
    backToDirectory: "रुग्ण निर्देशिकेकडे परत",
    caseDetails: "केस तपशील",
    healthTimelineTab: "आरोग्य टाईमलाईन",
    familyTreeTab: "कुटुंब वृक्ष",
    aiIntakeSummary: "AI केस नोंदणी सारांश",
    verifiedViaIntake: "AI क्लिनिकल संवादाद्वारे सत्यापित",
    patientChiefComplaint: "रुग्णाची मुख्य तक्रार",
    durationAndSeverity: "कालावधी आणि तीव्रता",
    reportedSymptoms: "नोंदवलेली लक्षणे आणि टीप",
    clinicalVitals: "क्लिनिकल व्हायटल्स",
    ocrDocumentsAttached: "संलग्न OCR वैद्यकीय कागदपत्रे",
    clinicalDiagnosis: "क्लिनिकल निदान",
    diagnosisPlaceholder: "प्राथमिक क्लिनिकल निदान प्रविष्ट करा...",
    doctorNotes: "डॉक्टरांच्या नोंदी व सल्ला",
    notesPlaceholder: "क्लिनिकल निरीक्षणे, जीवनशैली सल्ला, फॉलो-अप शिफारसी...",
    prescribedMedications: "औषधे प्रिस्क्रिप्शन",
    addMedication: "+ औषध जोडा",
    medicineName: "औषधाचे नाव",
    dosage: "मात्रा (Dosage)",
    frequency: "वारंवारता (Frequency)",
    duration: "कालावधी (Duration)",
    instructions: "सूचना / टीप",
    editIntakeData: "माहिती दुरुस्त / संपादित करा",
    printCaseSummary: "केस सारांश व Rx प्रिंट करा",
    confirmAndComplete: "सल्लामसलत पुष्टी व पूर्ण करा",
    consultationCompletedMsg: "सल्लामसलत पूर्ण झाली आणि रेकॉर्ड समक्रमित झाले.",
  },

  hi: {
    // Navbar & Common
    carelink: "केयरलिंक",
    doctorPortal: "डॉक्टर पोर्टल",
    patientPortal: "मरीज पोर्टल",
    doctorLogin: "डॉक्टर लॉगिन",
    patientLogin: "मरीज लॉगिन",
    logout: "लॉग आउट",
    abhaVerified: "आभा सत्यापित",
    abhaId: "आभा आईडी",
    step1of3: "चरण 1 / 3",
    close: "बंद करें",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    save: "सुरक्षित करें",
    edit: "संपादित करें",
    print: "प्रिंट करें",
    status: "स्थिति",
    view: "देखें",
    open: "खोलें",
    explore: "देखें",

    // Login Page
    careJourney: "स्वास्थ्य यात्रा",
    healthInOnePlace: "आपका स्वास्थ्य, एक ही स्थान पर",
    healthInOnePlaceDesc: "अपना मेडिकल इतिहास साथ रखें, ताकि हर चिकित्सीय निर्णय अधिक व्यक्तिगत और सटीक हो सके।",
    welcomeBack: "वापसी पर स्वागत है",
    continueCareJourney: "आइए अपनी स्वास्थ्य यात्रा जारी रखें।",
    signInSubtitle: "अपने मेडिकल इतिहास और व्यक्तिगत परामर्श के लिए साइन इन करें।",
    loginWithAbha: "आभा (ABHA) से लॉगिन",
    loginWithMobile: "मोबाइल नंबर से लॉगिन",
    enterAbhaId: "अपना आभा (ABHA) आईडी दर्ज करें",
    enterMobileNumber: "अपना मोबाइल नंबर दर्ज करें",
    verifyAndSignIn: "सत्यापित करें व साइन इन करें",
    newToAbha: "आभा आईडी नहीं है?",
    createAbhaDesc: "2 मिनट में अपना आयुष्मान भारत स्वास्थ्य खाता (ABHA) बनाएं।",
    createAbha: "आभा आईडी बनाएं",
    doctorOrHospitalStaff: "डॉक्टर या अस्पताल कर्मी हैं?",
    accessDoctorWorkstation: "डॉक्टर वर्कस्टेशन और ओपीडी डेस्क का उपयोग करें।",
    switchToDoctorLogin: "डॉक्टर पोर्टल पर जाएं →",
    switchToPatientLogin: "मरीज पोर्टल पर जाएं →",

    // Doctor Login
    doctorPortalTitle: "क्लिनिकल सेवा, सरल और सुव्यवस्थित",
    doctorPortalDesc: "परामर्श रिकॉर्ड देखें, पर्चे लिखें और मरीज का इतिहास सुरक्षित रूप से जांचें।",
    doctorSignInHeading: "डॉक्टर साइन इन",
    doctorSignInDesc: "अपने परामर्श वर्कस्टेशन तक पहुंचने के लिए पंजीकृत मोबाइल नंबर दर्ज करें।",
    registeredMobileNumber: "पंजीकृत मोबाइल नंबर",
    verifyDoctorLogin: "सत्यापित करें व वर्कस्टेशन खोलें",
    areYouPatient: "क्या आप मरीज हैं?",
    patientPortalRedirect: "मरीज पोर्टल पर अपने आभा आईडी या मोबाइल नंबर से साइन इन करें।",

    // Profile Card
    confirmProfileDetails: "अपनी प्रोफ़ाइल जानकारी की पुष्टि करें",
    profileReviewDesc: "आगे बढ़ने से पहले अपने आभा रिकॉर्ड से प्राप्त व्यक्तिगत जानकारी की समीक्षा करें।",
    personalDetails: "व्यक्तिगत विवरण",
    fullName: "पूरा नाम",
    age: "उम्र",
    gender: "लिंग",
    abhaAddress: "आभा पता (ABHA Address)",
    confirmAndContinue: "पुष्टि करें और आगे बढ़ें",
    notYouSwitch: "आप नहीं हैं? खाता बदलें",

    // Consent Screen
    step2of3: "चरण 2 / 3",
    abdmConsentRequest: "ABDM सहमति अनुरोध",
    consentRequestSubtitle: "AI-सहायित परामर्श के लिए केयरलिंक आपके स्वास्थ्य रिकॉर्ड की सहमति मांगता है।",
    whatWeCollect: "हम क्या एकत्र करते हैं",
    whatWeCollectDesc: "आपकी आवाज के उत्तर, लक्षण और अपलोड किए गए मेडिकल दस्तावेज़।",
    howItIsUsed: "इसका उपयोग कैसे किया जाता है",
    howItIsUsedDesc: "परामर्श टोकन और डॉक्टर के लिए क्लिनिकल सारांश तैयार करने के लिए।",
    dataProtection: "डेटा सुरक्षा और गोपनीयता",
    dataProtectionDesc: "ABDM स्वास्थ्य डेटा प्रबंधन नीति के तहत पूर्णतः एन्क्रिप्टेड।",
    grantConsent: "सहमति दें और आगे बढ़ें",
    declineConsent: "अस्वीकार करें और वापस जाएं",

    // Patient Dashboard Header
    goodMorning: "शुभ प्रभात",
    portalSubtitle: "आपका सक्रिय परामर्श टोकन और डिजिटल मेडिकल रिकॉर्ड अद्यतित हैं।",
    startNewCase: "+ नया केस बनाएं",
    aiIntake: "AI परामर्श",
    startNewConsultation: "नया परामर्श शुरू करें",

    // Tabs
    overview: "अवलोकन",
    timeline: "टाइमलाइन",
    addHistory: "इतिहास जोड़ें",
    familyTree: "परिवार वृक्ष (Family Tree)",
    settings: "सेटिंग्स",

    // Quick Action Cards
    doctorScannerTitle: "डॉक्टर डेस्क स्कैनर",
    doctorScannerDesc: "ओपीडी में प्रवेश करते समय QR स्कैन करें",
    healthTimelineTitle: "स्वास्थ्य टाइमलाइन",
    healthTimelineDesc: "दर्ज की गई विज़िट और रिपोर्ट",
    addHistoryTitle: "मेडिकल रिकॉर्ड जोड़ें",
    addHistoryDesc: "पुराने पर्चे, लैब रिपोर्ट और OCR अपलोड करें",
    familyTreeTitle: "परिवार वृक्ष",
    familyTreeDesc: "जुड़े हुए पारिवारिक स्वास्थ्य खाते",

    // Active Token Card
    consultationToken: "परामर्श टोकन",
    currentActiveToken: "वर्तमान सक्रिय टोकन",
    noActiveConsultation: "कोई सक्रिय परामर्श नहीं है",
    noActiveConsultationDesc: "डॉक्टर से परामर्श करने के लिए AI परामर्श शुरू करें या डॉक्टर का QR कोड स्कैन करें।",
    readyToStart: "शुरू करने के लिए तैयार",
    activeConsultation: "सक्रिय परामर्श",
    checkedInViaQr: "कमरा QR द्वारा चेक-इन",
    awaitingQrCheckIn: "कमरा QR चेक-इन लंबित",
    consultationStatus: "परामर्श स्थिति",
    attendingOpd: "संबंधित डॉक्टर / ओपीडी",
    nonePendingQr: "कोई नहीं (QR स्कैन करें)",
    viewToken: "टोकन देखें",
    scanRoomQr: "कमरा QR स्कैन करें",
    myConsultationCases: "मेरे परामर्श केस",
    makeNewCase: "+ नया केस बनाएं",
    scanDoctorQrToComplete: "डेस्क चेक-इन पूरा करने के लिए डॉक्टर का QR कोड स्कैन करें।",
    scanAnyDoctorPrompt: "कैमरा सामने लाएं या किसी भी ओपीडी डॉक्टर डेस्क का QR स्कैन करें।",
    completed: "पूर्ण हुआ",
    awaitingRoomQr: "कमरा QR प्रतीक्षित",
    checkedIn: "चेक-इन पूर्ण",
    physician: "चिकित्सक",
    created: "बनाया गया",
    scanner: "स्कैनर",
    ayushHolistic: "आयुष समग्र",
    generalMedicine: "सामान्य चिकित्सा",
    chronologicalRecord: "कालक्रमानुसार रिकॉर्ड",
    digitalHealthTimeline: "डिजिटल स्वास्थ्य टाइमलाइन",
    timelineSubtitle: "ABDM स्वास्थ्य रिकॉर्ड और सत्यापित OPD विज़िट्स के साथ समन्वयित।",
    noRecordsFound: "कोई रिकॉर्ड नहीं मिला",
    noRecordsDesc: "परामर्श पूरा करें या रिकॉर्ड जोड़ने के लिए \"+ इतिहास जोड़ें\" का उपयोग करें।",
    selfReportedRecords: "स्व-रिपोर्ट किए गए स्वास्थ्य रिकॉर्ड",
    addPastMedicalRecord: "पिछला मेडिकल रिकॉर्ड और रिपोर्ट जोड़ें",
    addPastMedicalRecordDesc: "ABHA के साथ सिंक करने के लिए लैब रिपोर्ट या पिछले नुस्खे अपलोड करें।",
    familyMedicalTree: "पारिवारिक मेडिकल ट्री और वंशानुगत प्रोफ़ाइल",

    // Scanner Modal
    scannerTitle: "डॉक्टर डेस्क QR स्कैनर",
    scannerSubtitle: "कैमरा सामने लाएं या किसी भी डॉक्टर डेस्क QR कोड को स्कैन करें।",
    verifiedDoctorDesk: "सत्यापित डॉक्टर डेस्क",
    checkInExistingCase: "मौजूदा केस चेक-इन करें",
    startNewCaseForDoctor: "इस डॉक्टर के लिए नया केस बनाएं",
    scanDifferentDoctor: "दूसरा डॉक्टर कोड स्कैन करें",
    alignDoctorQr: "डॉक्टर QR कोड को बॉक्स के अंदर रखें",
    verifyQr: "QR सत्यापित करें",
    enterRoomCode: "कमरा कोड दर्ज करें (उदा. OPD-DEMOCARE-3)",
    quickTestPresets: "1-क्लिक टेस्ट डॉक्टर QR बैज:",

    // Family Tree
    familyHealthNetwork: "पारिवारिक स्वास्थ्य नेटवर्क",
    familyTreeSubtitle: "आनुवंशिक बीमारियों की पहचान और बेहतर देखभाल के लिए परिवार के आभा खाते जोड़ें।",
    addFamilyMember: "+ परिवार सदस्य जोड़ें",
    consentLinkedAbdm: "सहमति से जुड़ा (ABDM)",
    hereditaryInsight: "पारिवारिक आनुवंशिक स्वास्थ्य विश्लेषण",
    hereditaryDesc: "परिवार में उच्च रक्तचाप और मधुमेह का इतिहास दर्ज है। श्रीराम के लिए नियमित जांच की सलाह दी जाती है।",
    selfPatient: "स्वयं (मरीज)",
    sendConsentRequest: "ABDM द्वारा सहमति अनुरोध भेजें",
    simulateAccept: "सदस्य की सहमति स्वीकार करें",
    requestSent: "रिश्तेदार के आभा आईडी पर सहमति अनुरोध भेजा गया। स्वीकृति की प्रतीक्षा...",
    memberLinkedSuccess: "परिवार का सदस्य सफलतापूर्वक परिवार वृक्ष में जुड़ गया!",

    // Summary Token
    medicalHistoryReady: "आपका मेडिकल इतिहास तैयार है",
    medicalHistoryReadyDesc: "परामर्श के लिए बुलाने से पहले आपके डॉक्टर आपका स्वास्थ्य इतिहास और लक्षण देख सकते हैं।",
    tokenNumberLabel: "आपका टोकन नंबर",
    assignedOpdLabel: "निर्धारित ओपीडी डेस्क",
    tokenActiveNote: "आपका टोकन सक्रिय है। बुलाए जाने पर ओपीडी कक्ष में जाएं।",
    caseForwardedNote: "परामर्श तैयार · केस विवरण डॉक्टर वर्कस्टेशन पर भेज दिया गया है",
    backToDashboard: "डैशबोर्ड पर वापस जाएं",
    synchronizedWithAbdm: "ABDM के साथ समक्रमित",

    // Doctor Dashboard & Workstation
    doctorWorkstation: "डॉक्टर वर्कस्टेशन",
    todaysConsultations: "आज के सक्रिय परामर्श",
    todayAppointments: "आज की नियुक्तियां",
    viewAllPatients: "सभी मरीज देखें →",
    patientDirectory: "मरीज निर्देशिका",
    patientsAndRecords: "मरीज और क्लिनिकल रिकॉर्ड",
    patientsDirectoryDesc: "पंजीकृत मरीज फाइलें, चल रहे केस और आभा लिंक्ड इतिहास देखें।",
    deskQrPlacard: "डेस्क QR पट्टिका",
    pendingReviews: "समीक्षा के लिए लंबित",
    completedVisits: "पूर्ण हुए परामर्श",
    activeDoctorCode: "सक्रिय डॉक्टर डेस्क कोड",
    showDeskQr: "डेस्क QR दिखाएं",
    copyDeskCode: "डेस्क कोड कॉपी करें",
    openCase: "केस खोलें",
    openFile: "फ़ाइल खोलें",
    review: "समीक्षा करें",
    filterAll: "सभी मरीज",
    filterActive: "सक्रिय",
    filterRecent: "हाल ही के",
    backToDirectory: "मरीज निर्देशिका पर वापस",
    caseDetails: "केस विवरण",
    healthTimelineTab: "स्वास्थ्य टाइमलाइन",
    familyTreeTab: "परिवार वृक्ष",
    aiIntakeSummary: "AI केस परामर्श सारांश",
    verifiedViaIntake: "AI क्लिनिकल संवाद द्वारा सत्यापित",
    patientChiefComplaint: "मरीज की मुख्य शिकायत",
    durationAndSeverity: "अवधि और गंभीरता",
    reportedSymptoms: "दर्ज किए गए लक्षण और नोट्स",
    clinicalVitals: "क्लिनिकल वाइटल्स",
    ocrDocumentsAttached: "संलग्न OCR मेडिकल दस्तावेज़",
    clinicalDiagnosis: "क्लिनिकल निदान",
    diagnosisPlaceholder: "प्राथमिक क्लिनिकल निदान दर्ज करें...",
    doctorNotes: "डॉक्टर नोट्स व सलाह",
    notesPlaceholder: "क्लिनिकल अवलोकन, जीवनशैली सलाह, फॉलो-अप सिफारिशें...",
    prescribedMedications: "निर्धारित दवाएं",
    addMedication: "+ दवा जोड़ें",
    medicineName: "दवा का नाम",
    dosage: "खुराक (Dosage)",
    frequency: "आवृत्ति (Frequency)",
    duration: "अवधि (Duration)",
    instructions: "निर्देश / नोट्स",
    editIntakeData: "जानकारी सुधारें / संपादित करें",
    printCaseSummary: "केस सारांश व Rx प्रिंट करें",
    confirmAndComplete: "परामर्श पुष्टि व पूर्ण करें",
    consultationCompletedMsg: "परामर्श पूर्ण हुआ और रिकॉर्ड समक्रमित किया गया।",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("carelink_lang") as Language | null;
    if (saved && (saved === "en" || saved === "mr" || saved === "hi")) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("carelink_lang", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
